language: c
git:
  submodules: false

env: B=autotools

os: linux

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      gdb
      gradle-2.2.1
      libcap-dev
      libdbd-sqlite3
      libdbi0-dev
      libesmtp-dev
      libevtlog-dev
      libgeoip-dev
      libglib2.0-dev
      libhiredis-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libriemann-client-dev
      libwrap0-dev
      pkg-config
      sqlite3
      xsltproc
      criterion-dev
  - sudo pip install -r requirements.txt
before_script:
  - ulimit -c unlimited -S
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - ./configure
      CFLAGS=-Werror
      --prefix=$HOME/install/syslog-ng
      --with-ivykis=internal
      --with-mongoc=internal
      --with-librabbitmq=internal
      --with-jsonc=system
      --disable-env-wrapper
      --disable-memtrace
      --disable-java
      --enable-tcp-wrapper
      --enable-linux-caps
      --disable-sun-streams
      --disable-sql
      --enable-pacct
      --enable-manpages
      --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
      --enable-extra-warnings
script:
  - . tests/build-log-cflags-propagation.sh;
    if [ "$CC" = "gcc" ]; then
      export DISTCHECK_CONFIGURE_FLAGS="CFLAGS=-Werror --enable-extra-warnings";
      exec_prop_check "make distcheck V=1 --keep-going";
    fi
compiler:
  - gcc
after_failure:
  - COREFILE="./syslog-ng-3.8.1/_build/core"
  #- EXECUTABLE=`gdb --core "$COREFILE" --batch | grep 'Core was generated' | sed $'s/^.*\`//;s/\'.$//'`
  - file "$COREFILE"
  - readelf "$COREFILE" -a
  - gdb -c "$COREFILE" ./syslog-ng-3.8.1/_build/tests/unit/test_ringbuffer -ex "thread apply all bt" -ex "set pagination 0" -batch
