language: c
git:
  submodules: false

env: B=cmake

os: linux
dist: trusty

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      gradle-2.2.1
      libcap-dev
      libdbd-sqlite3
      libdbi0-dev
      libesmtp-dev
      libevtlog-dev
      libgeoip-dev
      libglib2.0-dev
      libhiredis-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libriemann-client-dev
      libwrap0-dev
      pkg-config
      sqlite3
      xsltproc
      criterion-dev
  - sudo pip install -r requirements.txt
compiler:
  - clang

script:
  - mkdir build
  - cd build
  - cmake
      -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
      ..
  - make
  - make test
  - make -j install

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
