name: AxoSyslog charts linter

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: charts/axosyslog

jobs:
  axosyslog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Linter
        run: |
          docker run -v${PWD}:${PWD} alpine/helm lint ${PWD}
