name: AxoSyslog snapshot image

on:
  workflow_dispatch:
    inputs:
      platforms:
        default: "linux/amd64,linux/arm64"
      type:
        description: 'Snapshot type'
        required: true
        default: 'branch'
        type: choice
        options:
          - branch
          - custom
      custom-image-tag:
        description: 'Custom container image tag name (only used if custom type is selected)'
        required: false
        type: string
        default: 'x.y.z-custom-image-tag'
  push:
    branches:
      - main

jobs:
  cleanup-untagged-images:
    permissions: write-all
    # needs: [publish-image]
    runs-on: ubuntu-latest
    steps:
      - uses: MrAnno/delete-untagged-ghcr-action@dry-run
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: axosyslog
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
